name: Manual Tasks

on: workflow_dispatch

jobs:
  manual:
    runs-on: windows-latest

    env:
      SigningCertificate: StereoKit_UWP_TemporaryKey.pfx
      Solution_Path: StereoKitTemplate.sln
      UWP_Project_Path: .\Platforms\StereoKit_UWP\StereoKit_UWP.csproj
      UWP_Project_Directory: .\Platforms\StereoKit_UWP\
      UWP_Project_Name: StereoKit_UWP

    steps:

    - name: Configure Pagefile
      uses: al-cheb/configure-pagefile-action@v1.3
      with:
        minimum-size: 32GB
        maximum-size: 32GB
        disk-root: "C:"
    
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1

    - name: Use tag
      run: echo ${{steps.tag.outputs.tag}}

    - name: Extract version from tag
      uses: Amadevus/pwsh-script@v1
      id: getVersion
      with:
        script: '("${{steps.tag.outputs.tag}}").Split("v")[1]'

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Build Standalone & Android Package
      run: dotnet publish -h